FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install \
        build-essential \
        clang-format \
        cmake
VOLUME /code
WORKDIR /code
CMD rm -f CMakeCache.txt && cmake . && make deb && rm -f CMakeCache.txt

