FROM debian:bullseye-slim as ultra

RUN apt-get update && apt-get -y install \
    git \
    build-essential \
    cmake
RUN git clone https://github.com/TravisWheelerLab/ULTRA.git
WORKDIR /ULTRA
RUN cmake . && \
    make && \
    cp ultra /

# -----------------------------------------------------------------------------

FROM debian:bullseye-slim

COPY --from=ultra /ultra /usr/local/bin/
RUN ultra -h

ENTRYPOINT [ "ultra" ]
