name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags
  pull_request:
    tags:
      - 'v*.*.*'  # Trigger only on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Create zip archive of binaries
        run: |
          mkdir build_output
          cp build/ultra build_output/
          zip -r binaries_${{ github.ref_name }}.zip build_output/
        shell: bash

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
